### PR TITLE
Make plugins define their own interfaces

### PR DESCRIPTION
**Pull request by j-maas**

### CODE REVIEW

**Comment by stevenrick** [comment]
Exciting to see some activity in this repository! Happened to notice this plugin-examples branch and remembered I had a [collection of samples on hand from a few years back](https://drive.google.com/drive/folders/1RVMXVbiBK8SvDmf2YrRtN13PKZviuqAa?usp=sharing) - the old code may no longer be compatible but might still have some useful information or examples within of how ChronoViz plugins were built and used circa 2014

**Comment by j-maas** [comment]
Thanks for sharing!

While I suspect that this branch changes many fundamental things, it's interesting to see what you developed plugins for. Thanks!

**Comment by j-maas** [comment]
There are a few important issues with this PR:

It requires Python to be installed at a specific location (#18).
Plugins freeze the interface when they run.

For both I am unable to find a solution. :(

**Comment by j-maas** [comment]
As this PR's branch was merged into `avkit`, I am closing the PR.

**Pull request closed without merging**
